In [1]:
import pandas as pd
import numpy as np

### Get the data

In [2]:
path = '/Users/bengieru/Desktop/NMA-DL/iSarcasm/iSarcasm_dataset/'

test_raw = 'rawdata/test.txt'
train_raw = 'rawdata/train.txt'

test_ids_raw = 'rawdata/test_only_ids.txt'
train_ids_raw = 'rawdata/train_only_ids.txt'

test_meta = 'metadata/metadata_test.csv'
train_meta = 'metadata/metadata_train.csv'

path_test_raw = path + test_raw
path_train_raw = path + train_raw

path_test_ids_raw = path + test_ids_raw
path_train_ids_raw = path + train_ids_raw

path_test_meta = path + test_meta
path_train_meta = path + train_meta

test_rawdata = pd.read_csv(path_test_raw, delimiter = '\t')
train_rawdata = pd.read_csv(path_train_raw, delimiter = '\t')

test_ids_rawdata = pd.read_csv(path_test_ids_raw, delimiter = '\t')
train_ids_rawdata = pd.read_csv(path_train_ids_raw, delimiter = '\t')

test_metadata = pd.read_csv(path_test_meta)
train_metadata = pd.read_csv(path_train_meta)

## Adjust the annoying zeros at the end of tweet ids due to the excel

In [3]:
train_rawdata['tweet_id'] = train_ids_rawdata['ids']
test_rawdata['tweet_id'] = test_ids_rawdata['ids']

In [4]:
columns_metadata = train_metadata.columns.tolist()
columns_rawdata = train_rawdata.columns.tolist()
#columns_metadata, columns_rawdata
train_metadata

,id,created_at,text,attachments.media,attachments.media_keys,attachments.poll.duration_minutes,attachments.poll.end_datetime,attachments.poll.id,attachments.poll.options,attachments.poll.voting_status,...,reply_settings,source,withheld.scope,withheld.copyright,withheld.country_codes,type,__twarc.retrieved_at,__twarc.url,__twarc.version,Unnamed: 93
0,1084373658745876480,2019-01-13T08:56:41.000Z,sorry but sue from the mediweight advert looks...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPhone,NaN,NaN,NaN,NaN,2021-08-05T15:41:14+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
1,812173001,2008-05-15T18:40:23.000Z,"@ziggah no death allowed, normal tazing",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter Web Client,NaN,NaN,NaN,replied_to,2021-08-05T15:41:14+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
2,812181186,2008-05-15T18:51:03.000Z,@davesnyder since this is fantasy can it be an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter Web Client,NaN,NaN,NaN,NaN,2021-08-05T15:41:14+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
3,1090338810125275136,2019-01-29T20:00:04.000Z,Pound falls as Parliament rejects an amendment...,[{}],"[""3_1090338807608676353""]",NaN,NaN,NaN,NaN,NaN,...,everyone,SocialFlow,NaN,NaN,NaN,quoted,2021-08-05T15:41:14+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
4,1090351571395899392,2019-01-29T20:50:47.000Z,"Good times, fun times here in Grand old Britan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter Web Client,NaN,NaN,NaN,NaN,2021-08-05T15:41:14+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3270,1131854999246524416,2019-05-24T09:30:35.000Z,why did i think “knackered” was a swear word w...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPhone,NaN,NaN,NaN,NaN,2021-08-05T15:41:31+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
3271,1171093461111660546,2019-09-09T16:10:13.000Z,where are the best places to get an academic d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPhone,NaN,NaN,NaN,NaN,2021-08-05T15:41:31+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
3272,1158305504575275009,2019-08-05T09:15:27.000Z,i accidentally just posted someone’s happy bir...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPhone,NaN,NaN,NaN,NaN,2021-08-05T15:41:31+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
3273,1145291654926147586,2019-06-30T11:23:03.000Z,I can confirm I am retiring from the consumpti...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPhone,NaN,NaN,NaN,NaN,2021-08-05T15:41:31+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
3274,1055962756380327937,2018-10-26T23:21:54.000Z,Haven’t stopped thinking about Doctor Who sinc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPhone,NaN,NaN,NaN,NaN,2021-08-05T15:41:31+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN

In [5]:
test_metadata

,id,created_at,text,attachments.media,attachments.media_keys,attachments.poll.duration_minutes,attachments.poll.end_datetime,attachments.poll.id,attachments.poll.options,attachments.poll.voting_status,...,reply_settings,source,withheld.scope,withheld.copyright,withheld.country_codes,type,__twarc.retrieved_at,__twarc.url,__twarc.version,Unnamed: 93
0,1086119014131208193,2019-01-18T04:32:06.000Z,I knew as soon as I heard Doing Ford was cutti...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for Android,NaN,NaN,NaN,NaN,2021-08-05T15:42:58+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
1,914242426755256320,2017-09-30T21:35:54.000Z,"Eating apple sauce, chicken thighs, broccoli, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter Web Client,NaN,NaN,NaN,NaN,2021-08-05T15:42:58+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
2,1089244670998265856,2019-01-26T19:32:21.000Z,The greatest crime in the world is not develop...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter Web Client,NaN,NaN,NaN,NaN,2021-08-05T15:42:58+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
3,1065046825613344768,2018-11-21T00:58:45.000Z,@DemetriusHarmon i get paid on friday and i’m ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPhone,NaN,NaN,NaN,NaN,2021-08-05T15:42:58+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
4,1061820482872401920,2018-11-12T03:18:25.000Z,"No, please, no.\n\nOpinion: Hillary Will Run A...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPad,NaN,NaN,NaN,NaN,2021-08-05T15:42:58+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,1176203295939055616,2019-09-23T18:34:53.000Z,Imagine that it's going to cost me 600 pound t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter Web App,NaN,NaN,NaN,NaN,2021-08-05T15:43:03+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
805,1142855432295387142,2019-06-23T18:02:22.000Z,"people really out here tryna argue ""you don't ...","[{""width"": 250, ""preview_image_url"": ""https://...","[""16_1142855293832957953""]",NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter Web Client,NaN,NaN,NaN,NaN,2021-08-05T15:43:03+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
806,1170414497535799296,2019-09-07T19:12:16.000Z,@ArmyWP_Football and their relentless running ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for Android,NaN,NaN,NaN,NaN,2021-08-05T15:43:03+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
807,88500248498024448,2011-07-06T06:51:18.000Z,Why is it that whether I get out of bed at 6.4...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,HTC Peep,NaN,NaN,NaN,NaN,2021-08-05T15:43:03+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN
808,1133433248158277632,2019-05-28T18:01:59.000Z,Honestly this morning’s news about Gavin and S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,everyone,Twitter for iPhone,NaN,NaN,NaN,NaN,2021-08-05T15:43:03+00:00,https://api.twitter.com/2/tweets?expansions=au...,2.3.12,NaN

In [6]:
#train_cleandata = train_metadata
#test_cleandata = test_metadata
#test_cleandata['text'] = np.NaN
#train_cleandata['text'] = np.NaN

## Create empty DataFrames of the respective sizes

In [7]:
a = np.empty((3275,3))
a[:] = np.NaN
b = np.empty((809,3))
b[:] = np.NaN
train_cleandata = pd.DataFrame(a, columns = ['text', 'label', 'source'])
test_cleandata = pd.DataFrame(b, columns = ['text', 'label', 'source'])

### Adjust the tweet ids that doesn't exist anymore and label tweets as Sarcastic(True) and Not_Sarcastic(False)

In [8]:
for i,e in enumerate(train_rawdata['tweet_id']):
    for j,f in enumerate(train_metadata['id']):
        if e == f:
            train_cleandata['text'].iloc[j] = train_metadata['text'].iloc[j]
            train_cleandata['source'].iloc[j] = int(3)
            if train_rawdata['sarcasm_label'].iloc[i] == 'sarcastic':
                train_cleandata['label'].iloc[j] = True
            elif train_rawdata['sarcasm_label'].iloc[i] == 'not_sarcastic':
                train_cleandata['label'].iloc[j] = False
            #train_cleandata['text'][i] = train_metadata['text'][j]

for i,e in enumerate(test_rawdata['tweet_id']):
    for j,f in enumerate(test_metadata['id']):
        if e == f:
            test_cleandata['text'].iloc[j] = test_metadata['text'].iloc[j]
            test_cleandata['source'].iloc[j] = int(3)
            if test_rawdata['sarcasm_label'].iloc[i] == 'sarcastic':
                test_cleandata['label'].iloc[j] = True
            elif test_rawdata['sarcasm_label'].iloc[i] == 'not_sarcastic':
                test_cleandata['label'].iloc[j] = False
            #train_cleandata['text'][i] = train_metadata['text'][j]

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [9]:
#train_cleandata.to_csv(path + 'cleandata/train.csv')
train_cleandata

                                                   text  label  source
0     sorry but sue from the mediweight advert looks...  False     3.0
1                                                   NaN    NaN     NaN
2     @davesnyder since this is fantasy can it be an...  False     3.0
3                                                   NaN    NaN     NaN
4     Good times, fun times here in Grand old Britan...   True     3.0
...                                                 ...    ...     ...
3270  why did i think “knackered” was a swear word w...  False     3.0
3271  where are the best places to get an academic d...  False     3.0
3272  i accidentally just posted someone’s happy bir...  False     3.0
3273  I can confirm I am retiring from the consumpti...   True     3.0
3274  Haven’t stopped thinking about Doctor Who sinc...  False     3.0

[3275 rows x 3 columns]

In [10]:
#train_cleandata.to_csv(path + 'cleandata/test.csv')
test_cleandata

                                                  text  label  source
0    I knew as soon as I heard Doing Ford was cutti...  False     3.0
1    Eating apple sauce, chicken thighs, broccoli, ...  False     3.0
2    The greatest crime in the world is not develop...  False     3.0
3    @DemetriusHarmon i get paid on friday and i’m ...  False     3.0
4    No, please, no.\n\nOpinion: Hillary Will Run A...  False     3.0
..                                                 ...    ...     ...
804  Imagine that it's going to cost me 600 pound t...  False     3.0
805  people really out here tryna argue "you don't ...  False     3.0
806  @ArmyWP_Football and their relentless running ...  False     3.0
807  Why is it that whether I get out of bed at 6.4...  False     3.0
808  Honestly this morning’s news about Gavin and S...  False     3.0

[809 rows x 3 columns]

### Remove Nan rows

In [11]:
train_cleandata = train_cleandata.dropna()
train_cleandata

                                                   text  label  source
0     sorry but sue from the mediweight advert looks...  False     3.0
2     @davesnyder since this is fantasy can it be an...  False     3.0
4     Good times, fun times here in Grand old Britan...   True     3.0
5     I send light and love to all impacted by the #...  False     3.0
6                          Another year closer to death  False     3.0
...                                                 ...    ...     ...
3270  why did i think “knackered” was a swear word w...  False     3.0
3271  where are the best places to get an academic d...  False     3.0
3272  i accidentally just posted someone’s happy bir...  False     3.0
3273  I can confirm I am retiring from the consumpti...   True     3.0
3274  Haven’t stopped thinking about Doctor Who sinc...  False     3.0

[2847 rows x 3 columns]

In [12]:
test_cleandata = test_cleandata.dropna()
test_cleandata

                                                  text  label  source
0    I knew as soon as I heard Doing Ford was cutti...  False     3.0
1    Eating apple sauce, chicken thighs, broccoli, ...  False     3.0
2    The greatest crime in the world is not develop...  False     3.0
3    @DemetriusHarmon i get paid on friday and i’m ...  False     3.0
4    No, please, no.\n\nOpinion: Hillary Will Run A...  False     3.0
..                                                 ...    ...     ...
804  Imagine that it's going to cost me 600 pound t...  False     3.0
805  people really out here tryna argue "you don't ...  False     3.0
806  @ArmyWP_Football and their relentless running ...  False     3.0
807  Why is it that whether I get out of bed at 6.4...  False     3.0
808  Honestly this morning’s news about Gavin and S...  False     3.0

[709 rows x 3 columns]

### readjust indicies

In [13]:
train_cleandata.reset_index(drop=True, inplace=True)
train_cleandata

                                                   text  label  source
0     sorry but sue from the mediweight advert looks...  False     3.0
1     @davesnyder since this is fantasy can it be an...  False     3.0
2     Good times, fun times here in Grand old Britan...   True     3.0
3     I send light and love to all impacted by the #...  False     3.0
4                          Another year closer to death  False     3.0
...                                                 ...    ...     ...
2842  why did i think “knackered” was a swear word w...  False     3.0
2843  where are the best places to get an academic d...  False     3.0
2844  i accidentally just posted someone’s happy bir...  False     3.0
2845  I can confirm I am retiring from the consumpti...   True     3.0
2846  Haven’t stopped thinking about Doctor Who sinc...  False     3.0

[2847 rows x 3 columns]

In [14]:
test_cleandata.reset_index(drop=True, inplace=True)
test_cleandata

                                                  text  label  source
0    I knew as soon as I heard Doing Ford was cutti...  False     3.0
1    Eating apple sauce, chicken thighs, broccoli, ...  False     3.0
2    The greatest crime in the world is not develop...  False     3.0
3    @DemetriusHarmon i get paid on friday and i’m ...  False     3.0
4    No, please, no.\n\nOpinion: Hillary Will Run A...  False     3.0
..                                                 ...    ...     ...
704  Imagine that it's going to cost me 600 pound t...  False     3.0
705  people really out here tryna argue "you don't ...  False     3.0
706  @ArmyWP_Football and their relentless running ...  False     3.0
707  Why is it that whether I get out of bed at 6.4...  False     3.0
708  Honestly this morning’s news about Gavin and S...  False     3.0

[709 rows x 3 columns]

## Save the files

In [15]:
train_cleandata.to_csv(path + 'cleandata/train.csv')

In [16]:
test_cleandata.to_csv(path + 'cleandata/test.csv')